import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-adresa',
  templateUrl: './adresa.component.html',
  styleUrls: ['./adresa.component.scss']
})
export class AdresaComponent implements OnInit {

  judete = [
    'TIMIS',
    'ALBA',
    'ARAD',
    'ARGES',
    'BACAU',
    'BIHOR',
    'BISTRITA-NASAUD',
    'BOTOSANI',
    'BRASOV',
    'BRAILA',
    'BUCURESTI',
    'BUZAU',
    'CARAS-SEVERIN',
    'CALARASI',
    'CLUJ',
    'CONSTANTA',
    'COVASNA',
    'DAMBOVITA',
    'DOLJ',
    'GALATI',
    'GIURGIU',
    'GORJ',
    'HARGHITA',
    'HUNEDOARA',
    'IALOMITA',
    'IASI',
    'ILFOV',
    'MARAMURES',
    'MEHEDINTI',
    'MURES',
    'NEAMT',
    'OLT',
    'PRAHOVA',
    'SATU MARE',
    'SALAJ',
    'SIBIU',
    'SUCEAVA',
    'TELEORMAN',
    'TULCEA',
    'VASLUI',
    'VALCEA',
    'VRANCEA'
  ];

  localitati = [
    'TIMISOARA',
    'ALBINA',
    'ALIOS',
    'ALTRINGEN',
    'BABSA',
    'BACOVA',
    'BALINT',
    'BALOSESTI',
    'BANLOC',
    'BARA',
    'BARATEAZ',
    'BARNA',
    'BATESTI',
    'BAZOS',
    'BAZOSU NOU',
    'BEBA VECHE',
    'BECICHERECU MIC',
    'BEGHEIU MIC',
    'BELINT',
    'BENCECU DE JOS',
    'BENCECU DE SUS',
    'BERECUTA',
    'BEREGSAU MARE',
    'BEREGSAU MIC',
    'BERINI',
    'BETHAUSEN',
    'BICHIGI',
    'BILED',
    'BIRDA',
    'BLAJOVA',
    'BOBDA',
    'BOGDA',
    'BODO',
    'BOLDUR',
    'BOTESTI',
    'BOTINESTI',
    'BRANESTI',
    'BREAZOVA',
    'BRESTEA',
    'BRESTOVAT',
    'BUCOVAT',
    'BULGARUS',
    'BULZA',
    'BUNEA MARE',
    'BUNEA MICA',
    'BUTIN',
    'BUZAD',
    'BUZIAS',
    'CADAR',
    'CALACEA',
    'CAPAT',
    'CARANI',
    'CARPINIS',
    'CEBZA',
    'CENAD',
    'CENEI',
    'CERNA',
    'CERNETEAZ',
    'CHERLOTENBURG',
    'CHECEA',
    'CHECHES',
    'CHEGLEVICI',
    'CHERESTUR',
    'CHEVERESU MARE',
    'CHISODA',
    'CHIZATAU',
    'CIACOVA',
    'CIRESU',
    'CIRESU MIC',
    'CLADOVA',
    'CLICIOVA',
    'CLOPODIA',
    'COLONIA BULGARA',
    'COLONIA FABRICII',
    'COLONIA MICA',
    'COMEAT',
    'COMLOSU MARE',
    'COMLOSU MIC',
    'CORNESTI',
    'COSARII',
    'COSAVA',
    'COSEVITA',
    'COSTEIU',
    'COSTEIU DE SUS',
    'COVACI',
    'CRAI NOU',
    'CRALOVAT',
    'CRICIOVA',
    'CRIVINA',
    'CRIVINA DE SUS',
    'CRIVOBARA',
    'CRUCENI',
    'CURTEA',
    'CUTINA',
    'DAROVA',
    'DEJAN',
    'DENTA',
    'DETA',
    'DINIAS',
    'DOBRESTI',
    'DOLAT',
    'DRAGOIESTI',
    'DRAGOMIRESTI',
    'DRAGSINA',
    'DRAGSINESTI',
    'DRINOVA',
    'DUBESTI',
    'DUBOZ',
    'DUDESTII NOI',
    'DUDESTII VECHI',
    'DUMBRAVA',
    'DUMBRAVITA',
    'FADIMAC',
    'FAGET',
    'FARASESTI',
    'FARDEA',
    'FERENDIA',
    'FIBIS',
    'FICATAR',
    'FOENI',
    'FOLEA',
    'GAD',
    'GAIU MIC',
    'GATAIA',
    'GAVOJDIA',
    'GELU',
    'GHERMAN',
    'GHILAD',
    'GHIRODA',
    'GHIZELA',
    'GIARMATA',
    'GIARMATA-VII',
    'GIERA',
    'GIROC',
    'GIULVAZ',
    'GLADNA MONTANA',
    'GLADNA ROMANA',
    'GOTTLOB',
    'GRABAT',
    'GRANICERII',
    'GROSI',
    'GRUNI',
    'HAUZESTI',
    'HERENDESTI',
    'HERNEACOVA',
    'HEZERIS',
    'HISIAS',
    'HITIAS',
    'HODONI',
    'HODOS',
    'HOMOJDIA',
    'HONORICI',
    'IANOVA',
    'ICLODA',
    'ICTAR-BUDINTI',
    'IECEA MARE',
    'IECEA MICA',
    'IERSNIC',
    'IGRIS',
    'IOHANISFELD',
    'IOSIF',
    'IOSIFALAU',
    'IVANDA',
    'IZVIN',
    'JABAR',
    'JAMU MARE',
    'JDIOARA',
    'JEBEL',
    'JENA',
    'JIMBOLIA',
    'JUPANESTI',
    'JUPANI',
    'JURESTI',
    'LAPUSNIC',
    'LATUNAS',
    'LENAUHEIM',
    'LEUCUSESTI',
    'LIEBLING',
    'LIVEZILE',
    'LOVRIN',
    'LUCARET',
    'LUGOJ',
    'LUGOJEL',
    'LUNCANII DE JOS',
    'LUNCANII DE SUS',
    'LUNGA',
    'MACEDONIA MAGURI',
    'MANASTIRE',
    'MANASTUR',
    'MARGINA',
    'MASLOC',
    'MATNICU MIC',
    'MORAVITA',
    'MOSNITA NOUA',
    'MOSNITA VECHE',
    'MURANI',
    'NADAS',
    'NADRAG',
    'NEMESESTI',
    'NERAU',
    'NEVRINCEA',
    'NITCHIDORF',
    'OBAD',
    'OFSENITA',
    'OHABA-LUNGA',
    'OHABA-ROMANA',
    'OHABA-FORGACI',
    'OLOSAG',
    'OPATITA',
    'ORTISOARA',
    'OTELEC',
    'OTVESTI',
    'PADURANI',
    'PADURENI',
    'PADURENI VICTOR VLAD',
    'PANIOVA',
    'PARTA',
    'PARTOS',
    'PARU',
    'PECIU NOU',
    'PEROCOSOVA',
    'PERIAM',
    'PESAC',
    'PETROASA MARE',
    'PETROMAN',
    'PETROVASELO',
    'PIETROASA',
    'PINI',
    'PISCHIA',
    'POGANESTI',
    'POIENI',
    'PORDEANU',
    'POVARGINA',
    'PUSTINIS',
    'RACHITA',
    'RACOVITA',
    'RADMANESTI',
    'RAUTI',
    'RECAS',
    'REMETEA MARE',
    'REMETEA MICA',
    'REMETEA-LUNCA',
    'ROMANESTI',
    'ROVINITA MARE',
    'ROVINITA MICA',
    'RUDICICA',
    'RUDNA',
    'SACALAZ',
    'SACENI',
    'SACOSU MARE',
    'SACOSU TURCESC',
    'SAG',
    'SALBAGEL',
    'SALCIUA NOUA',
    'SANANDREI',
    'SANDRA',
    'SANGEORGE',
    'SANMARTINU MAGHIAR',
    'SANMARTINU SARBESC',
    'SANMARTINU GERMAN',
    'SANMARTINU ROMAN',
    'SANNICOLAU MARE',
    'SANOVITA',
    'SANPETRU MARE',
    'SANPETRU MIC',
    'SARAVALE',
    'SARAZANI',
    'SARBOVA',
    'SATCHINEZ',
    'SCULIA',
    'SECAS',
    'SECEANI',
    'SEMLACU MARE',
    'SEMLACU MIC',
    'SILAGIU',
    'SINERSIG',
    'SINTAR',
    'SINTESTI',
    'SIPET',
    'SOCA',
    'SPATA',
    'STAMORA GERMANA',
    'STAMORA ROMANA',
    'STANCIOVA',
    'STIUCA',
    'SUDRIAS',
    'SURDUCU MIC',
    'SUSANI',
    'SUSTRA',
    'TAPIA',
    'TARGOVISTE',
    'TEMERESTI',
    'TEREMIA MARE',
    'TEREMIA MICA',
    'TES',
    'TIPARI',
    'TOAGER',
    'TOMESTI',
    'TOMNATIC',
    'TOPLA',
    'TOPOLOVATU MARE',
    'TOPOLOVATU MIC',
    'TORMAC',
    'TRAIAN VUIA',
    'UIHEI',
    'UIVAR',
    'ULIUC',
    'UNIP',
    'URSENI',
    'UTVIN',
    'VALCANI',
    'VALEA LUNGA ROMANA',
    'VARIAS',
    'VICTOR VLAD DE LA MARINA',
    'VISAG',
    'VIZEJDIA',
    'VIZMA',
    'VOITEG',
    'VUCOVA',
    'ZGRIBESTI',
    'ZOLT',
    'ZORANI'
  ];

  constructor() { }

  ngOnInit() {
  }

}
